server:
  servlet:
    context-path: /auth
  port: 18001
spring:
  application:
    name: auth-center
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path}/actuator/health
        tags: management.context-path=${server.servlet.context-path}
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
          show-sql: false
          database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          hibernate:
            ddl-auto: update
  freemarker:
      request-context-attribute: request
      cache: true
  mvc:
    view:
      prefix: /pages/


logging:
  file: logs/auth-center.log
